name: TerraRenderer
main: de.terranova.terraRenderer.TerraRenderer
version: ${version}
api-version: "1.21"

commands:
  debug:
    description: Debug info + spawn display above looked-at block
    usage: /debug
    permission: terrarenderer.debug
    permission-message: "You don't have permission to use this command."
